# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f96ea35f7b14e9424ea504a2ddf757ebabbd6e0ed40916e0bf1f562d1a0693aa109e1c5bb23414aec7526416ff8af6ad0daa326661db995d945286cd2e479d2

test:
  secret_key_base: b467eab34b2e61e193f59bfafd4de6b4a9e1a092d796ce6863ec6c1e526893f5445782914228ebda41d32215cd9eb843e13c2bbc98028fd713758d7b3e30fc59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
